const MonitorItems = [
  {
    name: "cdv-guard",
    price: "1200000000",
    size: "4.3",
    sd: false,
    intercommunicate: false,
    handyPhone: true,
    parkingOpener: true,
    touch: false,
    cart: true,
    mobileConnect: false,
    camera: true,
    twoPanelConnect: false,
    guard: true,
    extraLock: false,
  },
  {
    name: "cdv-43d",
    price: "561615",
    size: "8",
    sd: true,
    inConnectorOn: true,
    handyPhone: true,
    parkingOpener: true,
    touch: true,
    cart: false,
    mobileConnect: false,
    camera: false,
    twoPanelConnect: true,
    guard: true,
    extraLock: true,
  },
  {
    name: "cdv-43dm",
    price: "1200000",
    size: "4.6",
    sd: true,
    inConnectorOn: false,
    handyPhone: true,
    parkingOpener: false,
    touch: false,
    cart: false,
    mobileConnect: false,
    camera: false,
    twoPanelConnect: false,
    guard: true,
    extraLock: false,
  },
  {
    name: "cdv-43win",
    price: "1200000",
    size: "8",
    sd: false,
    inConnectorOn: true,
    handyPhone: true,
    parkingOpener: false,
    touch: true,
    cart: false,
    mobileConnect: true,
    camera: false,
    twoPard: true,
    guadrd: true,
    extraLock: true,
  },
  {
    name: "cdv-46b",
    price: "1200000",
    size: "8",
    sd: true,
    inConnectorOn: true,
    handyPhone: false,
    parkingOpener: true,
    touch: false,
    cart: true,
    mobileConnect: false,
    camera: false,
    twoPanelConnect: false,
    guard: false,
    extraLock: false,
  },
  {
    name: "cdv-46bm",
    price: "1200000",
    size: "4.3",
    sd: true,
    inConnectorOn: false,
    handyPhone: true,
    parkingOpener: true,
    touch: true,
    cart: true,
    mobileConnect: true,
    camera: false,
    twoPanelConnect: true,
    guard: true,
    extraLock: true,
  },
  {
    name: "cdv-51d",
    price: "1200000",
    size: "7",
    sd: true,
    inConnectorOn: true,
    handyPhone: true,
    parkingOpener: true,
    touch: false,
    cart: true,
    mobileConnect: false,
    camera: true,
    twoPanelConnect: true,
    guard: false,
    extraLock: true,
  },
  {
    name: "cdv-51dm",
    price: "1200000",
    size: "4.6",
    sd: false,
    inConnectorOn: true,
    handyPhone: false,
    parkingOpener: true,
    touch: false,
    cart: true,
    mobileConnect: false,
    camera: true,
    twoPanelConnect: true,
    guard: false,
    extraLock: true,
  },
  {
    name: "cdv-70ms4",
    price: "1200000",
    size: "5.1",
    sd: true,
    inConnectorOn: false,
    handyPhone: true,
    parkingOpener: false,
    touch: false,
    cart: true,
    mobileConnect: false,
    camera: true,
    twoPanelConnect: true,
    guard: true,
    extraLock: true,
  },
  {
    name: "cdv-70t4",
    price: "1200000",
    size: "4.3",
    sd: true,
    inConnectorOn: true,
    handyPhone: true,
    parkingOpener: true,
    touch: true,
    cart: true,
    mobileConnect: false,
    camera: false,
    twoPanelConnect: true,
    guard: true,
    extraLock: false,
  },
  {
    name: "cdv-70tm4",
    price: "1200000",
    size: "7",
    sd: false,
    inConnectorOn: false,
    handyPhone: false,
    parkingOpener: true,
    touch: false,
    cart: true,
    mobileConnect: true,
    camera: false,
    twoPanelConnect: true,
    guard: true,
    extraLock: false,
  },
  {
    name: "cdv-70win",
    price: "1200000",
    size: "5.1",
    sd: true,
    inConnectorOn: true,
    handyPhone: true,
    parkingOpener: true,
    touch: false,
    cart: true,
    mobileConnect: false,
    camera: false,
    twoPanelConnect: false,
    guard: false,
    extraLock: false,
  },
  {
    name: "cdv-80ms4",
    price: "1200000",
    size: "7",
    sd: true,
    inConnectorOn: true,
    handyPhone: false,
    parkingOpener: true,
    touch: true,
    cart: true,
    mobileConnect: true,
    camera: true,
    twoPanelConnect: false,
    guard: false,
    extraLock: true,
  },
];

export default MonitorItems;
